function createHeadfigure1(Y1,Y2)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Jul-2018 10:57:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
subplot(2,1,1);
% Create plot
plot(Y1,'LineWidth',4);
% Create xlabel
xlabel({'Step (0.5 hr per step)'},'FontSize',15);

% Create title
title({'Head of tank8 (24 hrs without MPC)'},'FontSize',15);

% Create ylabel
ylabel({'Head8 (ft)'},'FontSize',15);
subplot(2,1,2);
% Create plot
plot(Y2,'LineWidth',4);
% Create xlabel
xlabel({'Step (0.5 hr per step)'},'FontSize',15);

% Create title
title({'Head of tank8 (3 hrs, k = 1, Hp = 5, reference = 838.8 )'},'FontSize',15);

% Create ylabel
ylabel({'Head8 (ft)'},'FontSize',15);

