function createHeadfigure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Jul-2018 10:57:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create xlabel
xlabel({'Time (0.5 hr)'},'FontSize',15);

% Create title
title({'Head of tank8'},'FontSize',15);

% Create ylabel
ylabel({'Head8 (ft)'},'FontSize',15);

box(axes1,'on');
