sed -i "s/\bans is a constraint \b//g" ~/Desktop/1.txt
sed -i ':a;N;$!ba;s/\n\n/\n/g' ~/Desktop/1.txt
sed -i ':a;N;$!ba;s/\n\n/\n/g' ~/Desktop/1.txt
sed -i "s/\bW_1\b/H_1/g" ~/Desktop/1.txt
sed -i "s/\bW_2\b/H_2/g" ~/Desktop/1.txt
sed -i "s/\bW_3\b/H_3/g" ~/Desktop/1.txt
sed -i "s/\bW_4\b/H_4/g" ~/Desktop/1.txt
sed -i "s/\bW_5\b/H_5/g" ~/Desktop/1.txt
sed -i "s/\bW_6\b/H_6/g" ~/Desktop/1.txt
sed -i "s/\bW_7\b/H_7/g" ~/Desktop/1.txt
sed -i "s/\bW_8\b/H_8/g" ~/Desktop/1.txt
sed -i "s/\bW_9\b/Q_1/g" ~/Desktop/1.txt
sed -i "s/\bW_10\b/Q_2/g" ~/Desktop/1.txt
sed -i "s/\bW_11\b/Q_3/g" ~/Desktop/1.txt
sed -i "s/\bW_12\b/Q_4/g" ~/Desktop/1.txt
sed -i "s/\bW_13\b/Q_5/g" ~/Desktop/1.txt
sed -i "s/\bW_14\b/Q_6/g" ~/Desktop/1.txt
sed -i "s/\bW_15\b/Q_7/g" ~/Desktop/1.txt
sed -i "s/\bW_16\b/Q_8/g" ~/Desktop/1.txt
sed -i "s/\bW_17\b/Q_9/g" ~/Desktop/1.txt
sed -i "s/\bW_18\b/S_1/g" ~/Desktop/1.txt

sed -i "s/\bans is a constraint \b//g" ~/Desktop/2.txt
sed -i ':a;N;$!ba;s/\n\n/\n/g' ~/Desktop/2.txt
sed -i ':a;N;$!ba;s/\n\n/\n/g' ~/Desktop/2.txt
sed -i "s/\bW_1\b/H_2/g" ~/Desktop/2.txt
sed -i "s/\bW_2\b/H_3/g" ~/Desktop/2.txt
sed -i "s/\bW_3\b/H_4/g" ~/Desktop/2.txt
sed -i "s/\bW_4\b/H_5/g" ~/Desktop/2.txt
sed -i "s/\bW_5\b/H_6/g" ~/Desktop/2.txt
sed -i "s/\bW_6\b/H_7/g" ~/Desktop/2.txt
sed -i "s/\bW_7\b/H_1/g" ~/Desktop/2.txt
sed -i "s/\bW_8\b/H_8/g" ~/Desktop/2.txt
sed -i "s/\bW_9\b/Q_1/g" ~/Desktop/2.txt
sed -i "s/\bW_10\b/Q_2/g" ~/Desktop/2.txt
sed -i "s/\bW_11\b/Q_3/g" ~/Desktop/2.txt
sed -i "s/\bW_12\b/Q_4/g" ~/Desktop/2.txt
sed -i "s/\bW_13\b/Q_5/g" ~/Desktop/2.txt
sed -i "s/\bW_14\b/Q_6/g" ~/Desktop/2.txt
sed -i "s/\bW_15\b/Q_7/g" ~/Desktop/2.txt
sed -i "s/\bW_16\b/Q_8/g" ~/Desktop/2.txt
sed -i "s/\bW_17\b/Q_9/g" ~/Desktop/2.txt
sed -i "s/\bW_18\b/S_1/g" ~/Desktop/2.txt
